### ISSUE TITLE
[Feature Request] Add the Abbility to share the Map with moer than three Chars/Corps/Alliances

### ISSUE THREAD

**Issue by Dark-Aeon** [exodus4d/pathfinder#222]
I just tried to share a Map with an Allaince a Corp and a couple of characters. It was only Possible to share between up to 3 Corporations or only 3 Alliances or 3 Characters but its not possible to mix and match.

Beeing Able to Mix and match in Map sharing would be awesome.

**Comment by IvandaNothabeer** [comment]
Its in the config file already

**Comment by Dark-Aeon** [comment]
ty for your answer :-) is the mix and match limitation between Corp/Alliance and Character also in the config file?

**Comment by exodus4d** [comment]
No it is not. 
This features is not implemented. I´m not sure If I´ll add something like this in future. It is not on top of my *TODO* list ;)

**Comment by Dark-Aeon** [comment]
ty for the Information and quick reply :-) I would love such a feature because Our Alliance wants to share the maps with some out of Alliance Corps and Characters. (Neutral alts) and adding all Corps in the Alliance plus the Out of Alliance Corps is working but then we cant add Characters in NPC coprs.

**Comment by IvandaNothabeer** [comment]
The issue is in the way that the "Search" feature is implemented and the way that the database splits Users, Corps, and Alliances into separate models. From my initial reading of the code, its a major job to change this.

**Comment by exodus4d** [comment]
No it is not hard to implement this. but it wil will take some time, but it isn´t complex.

Background tasks:
The way it should be working is, just to add some additional datatabase entries for a map in `character_map`, `corporation_map`, `alliance_map`. So a map could have multiple connections between multiple entity types (chars, corps, ally). 
After this we should ignore the "map_type" column in "maps" table, and add some additinal code in [charactermodel.php#L517](https://github.com/exodus4d/pathfinder/blob/master/app/main/model/charactermodel.php#L517)

Frontend tasks:
Adjust the UI for map sharing options. This will also need a refactoring for some templates and javascript functions.

It is nothing I´ll implement in 2016, thats for sure :)

**Comment by dkrotil** [comment]
I tried to share map with more that 3 corps and settings in pathfinder.ini is not honored. 

[PATHFINDER.MAP.CORPORATION]
LIFETIME                    =   99999
MAX_COUNT                   =   4
MAX_SHARED                  =   5
MAX_SYSTEMS                 =   100
ACTIVITY_LOGGING            =   1

still showing max 3 corps

**Comment by exodus4d** [comment]
@dkrotil  clear your cache after changed in `pathfinder.ini` were made, or wait for 1h (default cache time for  map settings). I don´t have problems with the share limit. Verify the small letter below the search field should have changed: 
![vmm123u](https://cloud.githubusercontent.com/assets/9299033/25773457/c667fbce-327d-11e7-9b6b-fdf9ed3a7d5b.png)

**Comment by dkrotil** [comment]
Clearing the cache did the trick, it´s working now.

**Comment by GhostShell77** [comment]
hi ! 
What about this fonctionnality now ? it will be fine to have it and share between alliance, corp or char whithout map type !
Thank you.

**Comment by AmraNiYesta** [comment]
But, a new patched arrived, we can share bookmarks and something is missing, I had to return on tripwire ... I am not able to add individual pilotes and i have a bad limite of who i can add to my map access list. We really need that on pathfinder, then, I think, we will have the best mapper we can find.

**Comment by Sjolus** [comment]
I'll throw the "mix and match" stuff a good ol' +1. We run a corp map but for some situations, we'd like to offer it up to some alliances, some specific corps in some alliances, etc etc. Love Pathfinder and all that it gives us, but this is a thorn in the side every now and then 🤗
