### ISSUE TITLE
ESI Errors

### ISSUE THREAD

**Issue by Ordo-Vhett** [exodus4d/pathfinder#519]
![image](https://user-images.githubusercontent.com/28077119/29390816-d8594a84-82c0-11e7-9734-6b8469a9342b.png)
Just started getting errors after today's update. seems CCP must have changed something on the ESI side

**Comment by Elpho910** [comment]
I am also getting these exact same issues since the patch.  Nothing to do with the ESI is working.

**Comment by jensar-antak** [comment]
*From Tweetfleet Slack*:

CCP Bartender [6:55 PM] 
Hey all, I'm going to have to offline universe/names again

[6:55] 
the instability is back and I can't triage it to my satisfaction, it'll have to go offline until tomorrow morning when we can deal with it properly

[6:55] 
sorry :disappointed:

___
Times in EDT. This isn't a Pathfinder bug, but rather the ESI endpoint being down temporarily.

**Comment by Elpho910** [comment]
Ah that makes sense, thanks for the info jensar

**Comment by exodus4d** [comment]
This was a problem on CCPs site.
I have a "non public" Slack channel ( in pathfinder-eve-online.slack.com) where I have set up some bots that follow CCPs Devs,  ESI monitoring, _EVE-Online_ server status, .... maybe it is a good option make this channel public and anyone who is interested about that information could get updated. Let me know.

![uq3jy2m](https://user-images.githubusercontent.com/9299033/29400955-7bcc1098-832f-11e7-9934-d17d6a7f5878.png)


Btw. please close issues that have been resolved. This would help me a lot keeping the Issues clean. Thanks :)

**Comment by generalluser** [comment]
I am still experiencing this issue. This error recurs for clients in logs/esi.error.client.log

```
[x.x.x.x] HTTP 404: 'Not Found' | url: GET 'https://esi.tech.ccp.is/v1/characters/123456789/online/?datasource=tranquility' | body: stdClass Object
(
    [error] => Not found
)
```

**Comment by generalluser** [comment]
> I have a "non public" Slack channel ( in pathfinder-eve-online.slack.com) where I have set up some bots that follow CCPs Devs, ESI monitoring, EVE-Online server status, .... maybe it is a good option make this channel public and anyone who is interested about that information could get updated. Let me know.

exodus4d I would appreciate the slack channel being public, or just an invite.
