### ISSUE TITLE
Can't build neighbour index and systems index

### ISSUE THREAD

**Issue by Flevity** [exodus4d/pathfinder#666]
structures and ships build succesfuly 
Building neighbour index process is stucking on wait..
Bulding systems index return an error 500
env:
clean pathfinder install
ubuntu 18.04
nginx 1.14.0
php-fpm 7.2.7
[nginx_error.log](https://github.com/exodus4d/pathfinder/files/2252184/nginx_error.log)
![image](https://user-images.githubusercontent.com/15307357/43565844-f632104e-9634-11e8-890f-d5eccb6fb03d.png)

**Comment by Slivo-fr** [comment]
Same here, tried about 50 time to build system index over 48h without any success

**Comment by Derjyn** [comment]
I third this. Glad I'm not the only one, was starting to drive me mad.

Ubuntu 16.04
Nginx 1.10.3
PHP 7.1.20

**Comment by exodus4d** [comment]
I know :( there is some kind of "race condition" between the Ajax build on /setup page and a Cronjob that runs every 60s und tries to update the static `eve_universe` DB.

1. Please comment out L60 https://github.com/exodus4d/pathfinder/blob/develop/app/cron.ini#L60
2. Wait 2min (makes sure there is no cronjob running for update)
3. Clear cache dir or _Redis_ DB
4. Go back to /setup page and retry building the systems index
5. Please let the cronjob (L60) deactivated until I fixed it in the next release. This is not a problem because CCP does not update static data that often 

> **Hint:**  Having the system index build up is not a **must have** its just a performance boost. _Pathinder_ automatically build the index for a system if it is missing in the index und requested for the first time.

**Comment by exodus4d** [comment]
If you get other problems in `1.4.0` please read this issue and check out my fix (`develop` branch):
https://github.com/exodus4d/pathfinder/issues/658#issuecomment-408164344

**Comment by Flevity** [comment]
I commented L60 and still cant build system indexes =_= error 500 and same error on nginx log.
I've tried to login into my pathfinder and after creating corp map there is an error 500 too =_=(mapmodel.php already replaced)

building indexs error:
``` 
2018/08/04 17:12:52 [error] 1167#1167: *9 FastCGI sent in stderr: "PHP message: HTTP 404 (GET /ws/map/update)
PHP message: [index.php:23] Base->run()" while reading response header from upstream, client: 2a02:2698:4c25:5392:9968:afa8:6097:7ef7, server: achtung-wh.tk, request: "GET /ws/map/update HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "achtung-wh.tk"
2018/08/04 17:13:08 [error] 1167#1167: *1 FastCGI sent in stderr: "PHP message: Call to a member function getAll() on boolean [/home/flevity/pathfinder/app/main/controller/ccp/universe.php:142]
PHP message: [app/main/controller/api/setup.php:64] Controller\Ccp\Universe->buildSystemsIndex()
PHP message: [index.php:23] Base->run()" while reading response header from upstream, client: 2a02:2698:4c25:5392:9968:afa8:6097:7ef7, server: achtung-wh.tk, request: "POST /api/setup/buildIndex HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "achtung-wh.tk", referrer: "https://achtung-wh.tk/setup"
```
after login error:
```
2018/08/04 17:14:13 [error] 1167#1167: *1 FastCGI sent in stderr: "PHP message: Validation failed: "systemId" = "31000713" [/home/flevity/pathfinder/app/main/model/basicmodel.php:463]
PHP message: [app/main/model/systemmodel.php:242] Model\BasicModel->throwValidationException()
PHP message: [app/main/model/basicmodel.php:311] Model\SystemModel->validate_systemId()
PHP message: [app/main/model/basicmodel.php:184] Model\BasicModel->validateField()
PHP message: [app/lib/magic.php:73] Model\BasicModel->set()
PHP message: [app/lib/magic.php:117] Magic->offsetset()
PHP message: [app/main/model/mapmodel.php:481] Magic->__set()
PHP message: [app/main/controller/api/map.php:993] Model\MapModel->getNewSystem()
PHP message: [app/main/controller/api/map.php:893] Controller\Api\Map->updateMapData()
```

**Comment by Derjyn** [comment]
Any updates on this? A bit hard to use this without this functionality.

**Comment by alewis-isc** [comment]
I'm having exactly this issue as well right now.

**Comment by justindh** [comment]
Figured out the issue with some trial and error, it looks like the eve_universe cache is struggling to build a system list from scratch. Dunno why, but this fixed it for me.

- In mysql, drop the eve_universe database `drop database eve_universe;` (your db name may very, checked environment.ini if you are unsure)
- 
- Now create a blank database `create database eve_universe;`
- 
- Import the eve_universe seeder [wiki](https://github.com/exodus4d/pathfinder/wiki/Database#user-content-3-import-initial-eve_universesql-db-dump) This step is still required! 
- 
- login to /setup and hit the setup tables button on eve-online universe section
- 
- login to /setup and hit the fix Columns/Keys button on eve-online universe section
- 
- clear cache
- 
- login to /setup and hit build system index build button
- 
- login to /setup and hit rest of the index data buttons after each finishes
- 
- profit?

**Comment by alewis-isc** [comment]
The above worked for me. Good work Sir!

**Comment by Tupsi** [comment]
tried this a few times now, no dice. still get the wrong counting and the counter never finishes

**Comment by lord-carlos** [comment]
Running latest /develop branch and still got this problem. (No redis)

Not sure how it should work, but apparently it did not import any systems via ESI. I had to import the .sql file.
Now when I build system index it just stops with server error 500. 
`/api/setup/buildIndex 500 (Internal Server Error)`

`2018/11/28 14:02:48 [error] 20441#20441: *21899 FastCGI sent in stderr: "PHP message: session_start(): Failed to decode session object. Session has been destroyed`

I'm gonna try it justindh way.

**Comment by exodus4d** [comment]
@lord-carlos I was able to reproduce your error. This just happens if "MySQL Sessions" are set in `config.ini` (which is the default). Installations with" _Redis_" configured instead of "_MySQL Sessions_" are not affected.

`2018/11/28 14:02:48 [error] 20441#20441: *21899 FastCGI sent in stderr: "PHP message: session_start(): Failed to decode session object. Session has been destroyed`

#### The problem
Building the "system Index" throws a huge amount of _temp_ data into the users Session. The default column type in `sessions`.`data` is `TEXT` which can not handle all and cuts off data `ON INSERT`... Next time Session data gets accessed fails because of invalid format -> `decode failed` 

#### Fix
Session DB table now has `MEDIUMTEXT` instead of `TEXT` as type for  `sessions`.`data` column
