### ISSUE TITLE
System is slow and connection won't delete

### ISSUE THREAD

**Issue by CalMatar** [exodus4d/pathfinder#820]
Since the update I am having issues logging in. It is taking a while to log in. I am sure it is not that big of a deal but thought you should know. 
The main reason for this ticket is that I can not seem to get a system deleted from my map. I have deleted it six times so far, I have even moved it and deleted it, and it keeps coming back to the same position. I am including pics to show.
![Screenshot_66](https://user-images.githubusercontent.com/42744905/61594603-a9f2b380-abbb-11e9-9407-2fcc7b61ef08.png)
![Screenshot_67](https://user-images.githubusercontent.com/42744905/61594604-a9f2b380-abbb-11e9-9bea-3930e3282881.png)
![Screenshot_68](https://user-images.githubusercontent.com/42744905/61594605-a9f2b380-abbb-11e9-8215-128a8b89641a.png)
![Screenshot_69](https://user-images.githubusercontent.com/42744905/61594606-aa8b4a00-abbb-11e9-8b75-0a8eecf4f07a.png)

**Comment by CalMatar** [comment]
I just noticed that while updating signatures in my home hole and also while updating intel in a neighboring hole I am getting the warning that I am not in this hole and do I still want to do this while I am in fact in that particular hole and it shows this on the map. 
![Screenshot_70](https://user-images.githubusercontent.com/42744905/61594929-f12e7380-abbe-11e9-981f-5ed7ad66461d.png)

**Comment by CalMatar** [comment]
Also, the system is extremely slow, almost as slow as it was when you had the timeout issue before.

**Comment by exodus4d** [comment]
@CalMatar Thanks for your report! 
### "_Server is slow_":
I had to do some _extended maintenance_ issues to do the last 2 days. I had to restart several services multiple times, testing new configurations,... 
As a result I had to **offline** all _MariaDB_ **slave** replication instances over the day which led to slow server responses because DB queries queued up and could not be handled just by the DB **master** server.
I have to watch the monitoring over the next days how it turns out.
I have also hot-fixed some _PHP_ errors over the day (e.g. clients get kicked out, log in issues,...)

### _"Systems won´t delete"_:
This is not _really a bug_. I saw the same issue, figured out the root cause and came to the result, that it is _intended behavior_. I´m open for suggestions! What happens:
1. You jumped from `Mehatoor` → `Home Hole` (verified by the new jump history _breadcrumb_ in the screens)
2. A new WH connection was created. (your map `scope` must be set to `wormhole` or `all`)
3. If you manually delete the system of your **previous location**, _Pathfinder_ **re-adds** the system with the next _update cycle_. _PF_ runs the same function which adds new connections based on the map `scope` by comparing your jump history data (which has not changed in the mean time).

Maybe we add some additional `timestamp` checks, and don´t **re-add** a system if it was manually deleted in the mean time...
... or we could "_auto temp lock_" the prev jumped system on map from been deleted...

**Comment by AtollEVE** [comment]
Me and my corp are also having lots of issues with systems refusing to be deleted from the map. One system we had a large lowsec fight in several days ago, keeps being added to our chain automatically even though it was never part of our WH chain to begin with. 

Deleted systems are added back to the map automatically within a few seconds, often with double or triple connection to the previously linked system. 

And as others have mentioned above we are also having the tracking error, where it asks if we are sure we wish to update sigs as we are not in that particular WH, depsite being in that location at the time.

**Comment by tralafiti** [comment]
> If you manually delete the system of your previous location, Pathfinder re-adds the system with the next update cycle. PF runs the same function which adds new connections based on the map scope by comparing your jump history data (which has not changed in the mean time).

If I understand this correctly this will lead to all kind of wired situations when you live in a wh. For example if we rage role (scan static, jump scout in, maybe scout 1 wh out, scout comes back, close static, scan new static and repeat) we would be unable to delete the chain since the scout has the systems in his history. Making it impossible to delete these systems ("auto temp lock") would only lead to a map full of systems we aren't connected to anymore - this kinda makes the whole mapping part useless to be honest 😅 . Checking timestamps and prevent systems from beeing auto-re-added if it was deleted manually in the mean time seems like a solution. 

This "re-add from history" feature was added to automatically add "missing" systems if ESI location was to slow to track every system?

**Comment by CalMatar** [comment]
Actually @exodus4d the problem is that there was NEVER an actual connection to Mehatoor. One of the people in the WH death cloned out to play around in K-space and that is where the connection came from. Since the map is a Wormhole Only map that is what the connection saw it as, a WH to Mehatoor. I don't mind that part but it was the not deleting part that bothered me, which I see is fixed now since it is no longer there and I was able to delete an EOL'd connection off of the map as well. Thank you. The slowness seems to be working good again. I will leave the ticket open for one more day to ensure other people that were having the same issue have it resolved as well.

**Comment by mrurb** [comment]
Yer I'm having to revert our pathfinder as this make our map completely useless. If a connection is deleted by a user, it should be deleted full stop. We often rage roll and this will mean that we have a lot of ghost systems hanging around that we can't get rid off.

**Comment by porowns** [comment]
Having to revert as well. Both issues are appearing for us. 

As for the "intended" feature, deleting old wormholes that no longer have connections attached still reappear in the top left. 

System also things that I'm in the wrong system, when I'm in the same system.

**Comment by CalMatar** [comment]
The only part of this that is still a problem is that the system identification is still not working. Everything else is working normally. When you delete things they delete as they should, at least on the public server.

**Comment by mrurb** [comment]
@CalMatar The problem with the warning has it own issuehere #821

And for not being able to delete systems is still a problem on the public pathfinder.
Reproducing steps:
1. Jump from wormhole A -> B
2. Jump from wormhole B -> A
3. Delete B from pathfinder
and about 5 seconds later the system gets added back in

**Comment by exodus4d** [comment]
@CalMatar I hot fixed my production server for #822 the commit should also fixe the re-added systems on map. The code is ugly but should work for now. Let me know if you see any issues

**Comment by CalMatar** [comment]
@exodus4d, as noted a little earlier that was fixed. The issues with the system not recognizing what system you are in when you try to update the signatures or Intel is still not working though. Everything is deleting correctly for me now. I appreciate everything you do. I am still in the midst of trying to get a stand alone server up and running but "things" have been kind of screwy here so I had to put it on hold. Let me know what you want me to check out and I can bug check any time.

**Comment by CalMatar** [comment]
> 
> 
> @CalMatar The problem with the warning has it own issue here #821
> 
> And for not being able to delete systems, it is still a problem on the public pathfinder.
> Reproducing steps:
> 
>     1. Jump from wormhole A -> B
> 
>     2. Jump from wormhole B -> A
> 
>     3. Delete B from pathfinder
>        and about 5 seconds later the system gets added back in

This was reported here first and I am using the public server as reported above.

**Comment by exodus4d** [comment]
I replaced the _ugly_ hotfix (9da2a78) with a proper solution.
The _checked_ state for historic "_jump records_", for new system/connection that should be added, is no longer a `timestamp` stored with the user `SESSION`.
The _checked_ state is now stored with the "_jump record_" data in cache:
- The **cronjob** now has access to it


#### There will be a new **Hotfix release** `v1.5.3` available, today
